[project]
name = "weather-web-app"
version = "0.1.0"
description = "A web app to display weather updates based on API data."
authors = ["Codelilok<codelilok@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "requests>=2.32.3",
]
